# Generated by Django 4.2.1 on 2023-09-29 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worker', '0018_remove_worker_area_remove_worker_city_and_more'),
        ('company', '0019_remove_company_area_remove_company_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerDeviceToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worker.worker')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDeviceToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
