# Generated by Django 4.2.1 on 2023-10-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydevicetoken',
            name='device_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workerdevicetoken',
            name='device_token',
            field=models.TextField(),
        ),
    ]
