# Generated by Django 4.2.1 on 2023-06-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=100)),
            ],
        ),
    ]
