# Generated by Django 4.2.1 on 2023-06-04 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='area',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.state'),
        ),
    ]
