# Generated by Django 4.2.1 on 2023-06-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_area_city_area_country_area_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('degree_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Degrees',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
