# Generated by Django 4.2.1 on 2023-09-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipAddress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('zip_code', models.CharField(max_length=50)),
                ('country_code', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city_en', models.CharField(blank=True, max_length=50, null=True)),
                ('state_en', models.CharField(blank=True, max_length=50, null=True)),
                ('state_code', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('province_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Zip Address',
            },
        ),
    ]
