# Generated by Django 3.2.4 on 2023-05-28 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('location_id', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line1', models.TextField()),
                ('address_line2', models.TextField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=30, null=True)),
                ('education_level', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_history', models.TextField(blank=True, null=True)),
                ('skill_set', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(max_length=50)),
                ('reference_id', models.CharField(max_length=255)),
                ('field_of_work', models.CharField(max_length=255)),
                ('photo', models.FileField(blank=True, null=True, upload_to='worker/images')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='worker/files')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.state')),
            ],
        ),
    ]
