# Generated by Django 4.2.1 on 2023-06-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_alter_jobapplication_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('degree_name', models.CharField(max_length=255)),
                ('institute', models.CharField(max_length=255)),
                ('passing_year', models.DateField(blank=True, null=True)),
                ('is_currently_reading', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('start_at', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('responsibilities', models.TextField()),
                ('is_currently_working', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='worker',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='location_id',
        ),
        migrations.AddField(
            model_name='worker',
            name='professional_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='worker',
            name='employment_history',
        ),
        migrations.AlterField(
            model_name='worker',
            name='field_of_work',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='reference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='worker',
            name='skill_set',
        ),
        migrations.AddField(
            model_name='worker',
            name='educations',
            field=models.ManyToManyField(to='worker.educationhistory'),
        ),
        migrations.AddField(
            model_name='worker',
            name='employment_history',
            field=models.ManyToManyField(blank=True, null=True, to='worker.employmenthistory'),
        ),
        migrations.AddField(
            model_name='worker',
            name='skill_set',
            field=models.ManyToManyField(to='worker.skill'),
        ),
    ]
