# Generated by Django 4.2.1 on 2023-06-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_degree_alter_city_options_alter_country_options'),
        ('worker', '0005_educationhistory_employmenthistory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationhistory',
            options={'verbose_name_plural': 'Education Histories'},
        ),
        migrations.AlterModelOptions(
            name='employmenthistory',
            options={'verbose_name_plural': 'Employment Histories'},
        ),
        migrations.RemoveField(
            model_name='educationhistory',
            name='degree_name',
        ),
        migrations.AddField(
            model_name='educationhistory',
            name='degree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.degree'),
            preserve_default=False,
        ),
    ]
