# Generated by Django 3.2.4 on 2023-06-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_gender'),
        ('worker', '0006_alter_educationhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.area'),
        ),
    ]
