# Generated by Django 3.2.4 on 2023-06-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0008_auto_20230609_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='is_profile_set',
        ),
    ]
