# Generated by Django 4.2.1 on 2023-08-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0014_educationhistory_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='account_status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Deactivate'), ('3', 'Deleted')], default=1, max_length=100),
        ),
    ]
