# Generated by Django 4.2.1 on 2023-08-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0015_worker_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='linkedin_profile',
            field=models.CharField(blank=True, null=True),
        ),
    ]
