# Generated by Django 4.2.1 on 2023-09-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0016_worker_linkedin_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='postal_code',
            new_name='zip_code',
        ),
    ]
