# Generated by Django 3.2.4 on 2023-05-28 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_contact_number', models.CharField(max_length=50)),
                ('company_address_line_1', models.TextField()),
                ('company_address_line_2', models.TextField(blank=True, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('contact_person_position', models.CharField(max_length=255)),
                ('contact_person_mobile', models.CharField(max_length=255)),
                ('contact_person_email', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.state')),
            ],
        ),
    ]
