# Generated by Django 4.2.1 on 2023-06-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_alter_jobapplication_job_id'),
        ('company', '0003_remove_job_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
