# Generated by Django 4.2.1 on 2023-06-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_delete_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='worker/images'),
        ),
    ]
