# Generated by Django 4.2.1 on 2023-06-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_company_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
