# Generated by Django 4.2.1 on 2023-06-05 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_gender'),
        ('company', '0006_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.area'),
        ),
    ]
