# Generated by Django 3.2.4 on 2023-06-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_type_name', models.CharField(max_length=100)),
            ],
        ),
    ]
