# Generated by Django 4.2.1 on 2023-06-05 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.companytype'),
            preserve_default=False,
        ),
    ]
