# Generated by Django 3.2.4 on 2023-06-05 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_companytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.companytype'),
            preserve_default=False,
        ),
    ]
