# Generated by Django 4.2.1 on 2023-06-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_company_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('industry_name', models.CharField(max_length=100)),
            ],
        ),
    ]
