# Generated by Django 4.2.1 on 2023-06-07 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_type',
        ),
    ]
