# Generated by Django 4.2.1 on 2023-06-07 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_remove_company_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.industry'),
            preserve_default=False,
        ),
    ]
