# Generated by Django 3.2.4 on 2023-07-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_alter_company_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
