# Generated by Django 4.2.1 on 2023-07-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20230715_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
