# Generated by Django 4.2.1 on 2023-09-19 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_zipaddress'),
        ('company', '0018_company_company_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='area',
        ),
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.RemoveField(
            model_name='company',
            name='state',
        ),
        migrations.AddField(
            model_name='company',
            name='zip_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.zipaddress'),
        ),
    ]
