# Generated by Django 4.2.1 on 2023-06-01 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_remove_job_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('job_for_trade', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_vacancies', models.IntegerField()),
                ('employment_status', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('application_deadline', models.DateTimeField()),
                ('cv_receiving_option', models.CharField(blank=True, max_length=255, null=True)),
                ('job_responsibilities', models.TextField(blank=True, null=True)),
                ('job_location', models.CharField(blank=True, max_length=30, null=True)),
                ('salary_type', models.CharField(blank=True, max_length=255, null=True)),
                ('trade_course_requirements', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_course_requirements', models.CharField(blank=True, max_length=255, null=True)),
                ('educational_requirements', models.CharField(blank=True, max_length=255, null=True)),
                ('age_restriction', models.IntegerField()),
                ('special_restrictions', models.TextField(blank=True, null=True)),
                ('experience_requirements', models.TextField(blank=True, null=True)),
                ('skills_requirements', models.TextField(blank=True, null=True)),
                ('gender_requirements', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobcategory')),
            ],
        ),
    ]
