# Generated by Django 4.2.1 on 2023-06-05 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_alter_educationhistory_options_and_more'),
        ('common', '0005_gender'),
        ('job', '0004_employmentstatus_jobbenefit_joblevel_jobtype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='age_restriction',
            new_name='age_require_maximum',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='salary',
            new_name='salary_range',
        ),
        migrations.RemoveField(
            model_name='job',
            name='educational_requirements',
        ),
        migrations.AddField(
            model_name='job',
            name='age_require_minimum',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.ManyToManyField(to='job.jobbenefit'),
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='degree_requirements',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.degree'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.joblevel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.jobtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='work_place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.workplace'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='job',
            name='cv_receiving_option',
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.employmentstatus'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='gender_requirements',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills_requirements',
        ),
        migrations.AddField(
            model_name='job',
            name='cv_receiving_option',
            field=models.ManyToManyField(to='job.resumereceivingoption'),
        ),
        migrations.AddField(
            model_name='job',
            name='gender_requirements',
            field=models.ManyToManyField(to='common.gender'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_requirements',
            field=models.ManyToManyField(to='worker.skill'),
        ),
    ]
