# Generated by Django 4.2.1 on 2023-06-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='category_icon',
            field=models.FileField(blank=True, null=True, upload_to='job/category/icons/'),
        ),
    ]
