# Generated by Django 4.2.1 on 2023-06-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_jobcategory_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPlacement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Job Placements',
            },
        ),
    ]
