# Generated by Django 4.2.1 on 2023-06-19 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_jobplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.jobplacement'),
        ),
    ]
