# Generated by Django 4.2.1 on 2023-06-19 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_gender'),
        ('job', '0010_alter_job_age_require_maximum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='degree_requirements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.degree'),
        ),
    ]
