# Generated by Django 3.2.4 on 2023-07-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_alter_job_degree_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('1', 'Draft'), ('2', 'Active'), ('2', 'Deactivate')], default=1, max_length=100),
        ),
    ]
