# Generated by Django 4.2.1 on 2023-07-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_job_job_description'),
        ('job', '0012_job_job_status'),
    ]

    operations = [
    ]
