# Generated by Django 4.2.1 on 2023-09-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_job_job_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Salary Types',
            },
        ),
    ]
