# Generated by Django 4.2.1 on 2023-09-17 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_salarytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary_type',
        ),
        migrations.AddField(
            model_name='job',
            name='salary_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.salarytype'),
        ),
    ]
